### ISSUE TITLE
Add method to change device's ID

### ISSUE THREAD

**Issue by Frankkkkk** [Frankkkkk/python-dds238#1]
We need to properly add a method in order to change the device's ID

**Comment by jcovington16** [comment]
What's the file that this method needs to be implemented in? What are the use cases?

**Comment by Frankkkkk** [comment]
Hi @jcovington16 , how can you be so quick ? I've just created the repo.. :-)

Anyways, it's useful when you've got multiple devices, as they can't have the same ID
Cheers

**Comment by jcovington16** [comment]
I was just looking for some open issues to tackle for the day and yours popped up quick lol. Ok so just to clarify you aren't changing the ID per say, you just want to be able to return multiple ID's if they are the same or not. Am I correct?

**Comment by Frankkkkk** [comment]
Hi @jcovington16 Sadly this was a hardware issue, so it's a bit complicated to implement without trying it on the hardware. You can check the commit as a curiosity.
Cheers

**Comment by jcovington16** [comment]
Oh ok no problem. I'll take a look at it. Thanks for letting me know.
